id: ID7390DB4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:22:21+00:00'
last_modified: '2022-06-07T19:03:07.822364+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG02533
  title: དམ་ཆོས་ཡིད་བཞིན་གྱི་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7B92:
      image_group_id: I00KG03136
      title: ''
      total_pages: 810
      order: 1
      base_file: 7B92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
