id: ID7390DB4
legacy_id: P003189
ocr_import_info:
  bdrc_scan_id: W00KG02533
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T07:17:22'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:54:08.668252+00:00'
last_modified: 2022-08-29 19:55:18.723982
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG02533
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG02533
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་ཡིད་བཞིན་གྱི་ནོར་བུ་ཐར་པ་རིན་པོ་ཆེའི་རྒྱན།
  author: སྒམ་པོ་པ་བསོད་ནམས་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.5397345835379197
  ocr_word_median_confidence_index: 0.5299999713897705
quality: null
bases:
  I00KG03136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03136
      total_pages: 810
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03136.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5397345835379197
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
